version: 2
jobs:
  build:
    docker:
      - image: cimg/clojure:1.12.0-openjdk-21.0-browsers
    steps:
      - run: which java
      - run: lein --version

      - checkout

      # Validate docs/cljdoc.edn
      - run: curl -fsSL https://raw.githubusercontent.com/cljdoc/cljdoc/master/script/verify-cljdoc-edn | bash -s docs/cljdoc.edn

      - run: sudo bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)

      - run: lein test

      - run: |
          cd core
          bb test:bb
